export const INITIAL_STATE = {
  dough: 0,
  owned: {},
  totalDoughEarned: 0,
  totalTaps: 0,
  runDoughEarned: 0,
  stars: 0,
  starUpgrades: {},
  achievements: [],
  stats: {
    playTime: 0,
    highestDps: 0,
    prestiges: 0,
    runStartedAt: Date.now(),
    goldenCaught: 0,
    goldenMissed: 0,
  },
  settings: {
    sfxVol: 0.7,
    musicVol: 0.3,
    notation: 'letter',
    theme: 'dark',
  },
  activeEffects: [],
  lastSaved: null,
  saveVersion: 2,
  ready: false,
  toast: null,
  resetArmed: false,
  activeTab: 'shop',
  goldenPizza: null,
  nextUpgradeDiscount: 0,
  bonusStarShards: 0,
  user: null,
  lastCloudSync: null,
};
